# Generated by Django 4.2.16 on 2024-11-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='finishtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
