# Generated by Django 4.2.16 on 2024-11-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_finishtime_alter_portfolio_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='kind',
            field=models.CharField(choices=[('club', '동아리'), ('volunteer', '봉사'), ('competition', '공모전/대회'), ('lecture', '학교강의')], max_length=50),
        ),
    ]
